name: Build Mozc Dictionary

on:
  workflow_dispatch:
  push:
    paths:
      - 'crates/mozc-dict-gen/**'
      - '.github/workflows/build_mozc_dict.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build and Run Generation
        run: |
          cargo run -p mozc-dict-gen --release

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mozc-vibrato-dict
          path: output/system.dic.zst
